language: java

jdk: openjdk8

install:
  - "./mvnw --show-version -Psonatype install -DskipTests=true -Dmaven.javadoc.skip=true -B -V"
before_script:
    # reset correct branch information
    - "./travis-set-branch.sh"
script:
    - "./mvnw --show-version -Psonatype -Prun-its clean install"

cache:
  directories:
    - $HOME/.m2

branches:
    except:
        - gh-pages

notifications:
  email:
    - matthieu@brouillard.fr
